name: Docker-Compose CI

on:
  push:
    paths:
      - 'docker-compose.yml'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Compose test
      run: docker-compose run --rm tesseractv1