name: Python Lint Check

on:
  push:
    branches: [main]
    paths:
      - '**.py'
  pull_request:
    branches: [main]
jobs:

  build:

    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v2  
    - name: Python Linter
      uses: sunnysid3up/python-linter@master
      with:
        source: "app"
        mypy-options: "--ignore-missing-imports --show-error-codes"
        pylint-options: "--rcfile=setup.cfg"
        
        