name: Python Lint Check

on:
  push:
    branches: [main]
    paths:
      - '**.py'
  pull_request:
    branches: [main]
jobs:

  build:

    runs-on: ubuntu-latest 
    steps:
    - uses: actions/checkout@v3
    - name: Install black
      run: pip install black && echo $GITHUB_WORKSPACE
    - name: Python Lint
      run: black $GITHUB_WORKSPACE 

        
        