name: Python Lint Check

on:
  push:
    branches: [main]
    paths:
      - '**.py'
  pull_request:
    branches: [main]
jobs:

  build:

    runs-on: ubuntu-latest 
    steps:
    - uses: piotrpawlaczek/python-blacken@release/stable
      with:
        path: $GITHUB_WORKSPACE

        
        